# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-12 21:05
from __future__ import unicode_literals

import EducaMasMainPage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EducaMasMainPage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='id_int',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Foto',
            field=models.FileField(upload_to=EducaMasMainPage.models.upload_image),
        ),
    ]
