# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-12 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EducaMasMainPage', '0002_auto_20180412_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Titulo',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
